import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

// import { logoutAdmin } from '@/utils/auth'
import { adminVar } from '@/apollo/reactiveVars'
import { gql, useMutation, useReactiveVar } from '@apollo/client'
import DashMain from '@/components/Layout/pages/dashActiveTasks'

export default function Home() {
  // get admin var data from apollo reactive variable
  const admin = useReactiveVar(adminVar)

  console.log('admin', admin);

  React.useEffect(() => {
    if (!admin || localStorage.getItem('major_project_admin') === '') {
      // redirect to login
      // window.location.href = '/login';
      console.log('redirect to login', admin)
    }
  }, [admin])

  function handleLogout() {
    // run the mutation for logging out the user
    logoutAdmin();
  }

  function onCompleted() {
    // clear admin data in apollo reactive variable
    adminVar(null)

    // update in local storage
    localStorage.setItem('major_project_admin', '');

    // redirect to login
    window.location.href = '/login';
  }


  const LOGOUT_ADMIN = gql`
    mutation logoutAdmin {
      logoutAdmin {
        message
      }
    }
  `

  const [logoutAdmin, { data, error, loading }] = useMutation(LOGOUT_ADMIN, {
    onCompleted,
  })

  if (error) {
    alert(`error logging out admin ${error}`)
  }

  // if (data) {
  //   alert(`admin logged out ${data}`)
  // }

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {admin && (<main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Welcome&nbsp;
            <code className={styles.code}>{admin?.email}</code>
          </p>
          <div>
            <button className={styles.logoutBtn} onClick={handleLogout}>Logout</button>
          </div>
        </div>

        {/* <div className={styles.tasks}>
          list
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div> */}

        {/* <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div> */}

        <DashMain />
      </main>)}
    </>
  )
}
